### PR TITLE
Apple Clone And Resolved Conflicts

### PR DESCRIPTION
**Pull request by HyperWoo**
Resolved Conflicts and Merge issues. #10 Sequel.

### CODE REVIEW

**Comment by HyperWoo** [comment]
@su1nta Sir, I have created a new fork to resolve the merge conflict that occurred due to multiple branch alterations. Pull Request is sent and will be happy to see the Apple_In_Clone "Live" on GitHub.

**Comment by su1nta** [comment]
@HyperWoo Everything seems nice and Apple-ish. Thank you for your valuable contribution. Happy Hacktoberfest!

**Comment by su1nta** [comment]
@HyperWoo The `CONTRIBUTING.md` file is added in the repo. Please add your details in the file, the writing convention is given in the README file.

**Comment by HyperWoo** [comment]
@su1nta I have successfully added my details in `CONTRIBUTING.md`. Thank you, for your guidance and the sharp opportunity to work with you. Happy Hacktoberfest!

**Pull request merged**
