### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DakshVarshney1409**
Added the required information. 
1. Added the Introduction to the repository
2. Added the technologies used.
3. Added the procedure for contributing

### CODE REVIEW

**Comment by su1nta** [comment]
Use code snippets as guidance in the contribution guide, @DakshVarshney1409. You can take reference from [here](https://github.com/su1nta/Originals#readme).

**Comment by DakshVarshney1409** [comment]
@su1nta I have done the necessary changes. Please check now.

**Review by su1nta — COMMENTED** [review]
@DakshVarshney1409 , you forgot to change the repo name in line 84 after pasting it from the reference file. Otherwise everything seems fine. Thanks for the contribution. Happy Hacktoberfest.

**Comment by su1nta** [comment]
@DakshVarshney1409 The `CONTRIBUTING.md` file is added in the repo. Please add your details in the file, the writing convention is given in the README file.

**Pull request merged**
